### ISSUE TITLE
Use `assert.InDelta` with epsilon over `assert.Equals` for float64

### ISSUE THREAD

**Issue by soumya92** [martinlindhe/unit#11]
To eliminate the `// round error, expected $actual` in tests, [`assert.InDelta`](https://godoc.org/github.com/stretchr/testify/assert#InDelta) with a small delta might be better.

Since units here represent physical units, it should not be too hard to pick a delta small enough to not matter, but large enough to paper over the floating point rounding errors.

**Comment by martinlindhe** [comment]
Sounds like a great idea! Help is welcome if you feel inclined.
