### ISSUE TITLE
Why hasn't there been a v1.0 released yet?

### ISSUE THREAD

**Issue by buggaarde** [martinlindhe/unit#18]
Most files haven't been touched for at least 3 years and there isn't much maintenance associated with a package that's mostly constants.

I think this package could see more use in projects (like the one I'm working on) that are a little hesitant about using a non-stable package, especially because it is essentially stable.

**Comment by martinlindhe** [comment]
It's a good idea. Let's make it happen!

**Comment by martinlindhe** [comment]
https://github.com/martinlindhe/unit/releases/tag/1.0.0
