### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lucasmezencio** [martinlindhe/unit#4]
Hi! I am a newbie Golang programmer.
So, sorry if my question is not a good question.

But can you help me?

```go
package util

import (
	"fmt"

	"github.com/martinlindhe/unit"
)

func main() {
	// It works! :)
	mb := 2 * unit.Megabyte

	fmt.Println(mb.Bytes())
	
	// It does not work! :(
	num := 2
	mb2 := num * unit.Megabyte
	
	fmt.Println(mb2.Bytes())
}
```

**Comment by martinlindhe** [comment]
You need to use the same number unit, or cast it to the same. unit uses float64, so you could either do

    num := 2.0 // implicit float64
    mb2 := num * unit.Megabyte

or cast it:
    // explicit float64
    num := 2
    mb2 := float64(num) * unit.Megabyte

hope that helps

**Comment by martinlindhe** [comment]
You need to use the same data type, so for example

    num := 2
    mb2 := unit.Datatype(num) * unit.Megabyte

hope that helps

**Comment by lucasmezencio** [comment]
@martinlindhe off course! thanks, dude! 😃

**Comment by alex88** [comment]
@martinlindhe sorry for the stupid question, but `unit.DataType` doesn't exists and `unit.Centimeter` isn't a function, having a float variable, how do I convert e.g. Centimeters to Inches?

**Comment by alex88** [comment]
Oh nvm found it `unit.Length(floatVal)`!

**Comment by martinlindhe** [comment]
Thanks for bringing this up again @alex88 

I have improved the README with better example usage and added this as code too in https://github.com/martinlindhe/unit/blob/master/example_test.go

**Comment by alex88** [comment]
Thanks @martinlindhe that helps! :)
